"use client";

import React, { useState } from "react";

interface JoinRoomModalProps {
  isOpen: boolean;
  onClose: () => void;
  onJoinSuccess?: (code: string) => void;
}

export default function JoinRoomModal({
  isOpen,
  onClose,
  onJoinSuccess,
}: JoinRoomModalProps) {
  const [inputCode, setInputCode] = useState("");
  const [status, setStatus] = useState<"idle" | "verifying" | "success" | "error">("idle");
  const [errorMessage, setErrorMessage] = useState("");

  if (!isOpen) return null;

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g, "");
    if (val.length <= 7) {
      setInputCode(val);
      if (status === "error") setStatus("idle");
    }
  };

  const handleJoin = () => {
    const clean = inputCode.trim();
    if (clean.length < 5) {
      setStatus("error");
      setErrorMessage("INVALID BREACH CODE FORMAT (e.g. CC-9821)");
      return;
    }

    setStatus("verifying");
    setTimeout(() => {
      if (clean.toLowerCase().includes("err")) {
        setStatus("error");
        setErrorMessage("ROOM EXPIRED OR CHAMBER FULL");
      } else {
        setStatus("success");
        setTimeout(() => {
          if (onJoinSuccess) onJoinSuccess(clean);
          onClose();
        }, 800);
      }
    }, 1000);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-md transition-all duration-200"
      onClick={onClose}
    >
      <div
        className="w-full max-w-md bg-surface-1 border border-border-subtle rounded-xl p-6 sm:p-7 flex flex-col gap-6 shadow-[0_20px_50px_rgba(0,0,0,0.85)] relative overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Glow accent */}
        <div className="absolute top-0 right-0 w-36 h-36 bg-secondary/5 rounded-full blur-2xl pointer-events-none"></div>

        {/* Modal Header */}
        <div className="flex items-center justify-between pb-4 border-b border-border-subtle">
          <div className="flex items-center gap-2.5">
            <span className="w-2.5 h-2.5 rounded-full bg-secondary"></span>
            <span className="font-system-eyebrow text-system-eyebrow text-text-muted uppercase">
              P2P TUNNEL // JOIN PEER CHAMBER
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded text-text-muted hover:text-text-primary hover:bg-surface-2 transition-colors cursor-pointer"
            type="button"
            aria-label="Close modal"
          >
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>

        {/* Description */}
        <p className="font-body-default text-xs text-text-secondary leading-relaxed">
          Input the 6-character room breach code generated by your peer to initiate low-latency P2P duel synchronization.
        </p>

        {/* Code Input */}
        <div className="space-y-2">
          <label className="font-system-eyebrow text-xs text-text-muted uppercase block">
            ENTER BREACH CODE
          </label>
          <div className="relative">
            <input
              type="text"
              value={inputCode}
              onChange={handleInputChange}
              placeholder="CC-8492"
              autoFocus
              className="w-full h-14 px-4 bg-surface-2 border border-border-subtle focus:border-primary-container focus:outline-none rounded font-mono text-2xl font-bold tracking-widest text-text-primary placeholder:text-text-muted text-center uppercase selection:bg-primary-container selection:text-[#080A0B]"
            />
            {inputCode && (
              <button
                type="button"
                onClick={() => setInputCode("")}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-text-muted hover:text-text-primary p-1 cursor-pointer"
              >
                <span className="material-symbols-outlined text-[18px]">cancel</span>
              </button>
            )}
          </div>

          {status === "error" && (
            <div className="flex items-center gap-1.5 text-status-failure text-xs font-code-snippet mt-1.5">
              <span className="material-symbols-outlined text-[14px]">error</span>
              <span>{errorMessage}</span>
            </div>
          )}

          {status === "success" && (
            <div className="flex items-center gap-1.5 text-status-success text-xs font-code-snippet mt-1.5">
              <span className="material-symbols-outlined text-[14px]">check_circle</span>
              <span>SYNCHRONIZED WITH PEER. CONNECTING...</span>
            </div>
          )}
        </div>

        {/* Quick Demo Pre-fill */}
        <div className="flex items-center gap-2 text-xs text-text-muted font-code-snippet">
          <span>Active demo rooms:</span>
          <button
            type="button"
            onClick={() => setInputCode("CC-9941")}
            className="px-1.5 py-0.5 rounded bg-surface-2 hover:bg-surface-3 text-secondary border border-border-subtle cursor-pointer font-mono"
          >
            CC-9941
          </button>
          <button
            type="button"
            onClick={() => setInputCode("CC-1048")}
            className="px-1.5 py-0.5 rounded bg-surface-2 hover:bg-surface-3 text-secondary border border-border-subtle cursor-pointer font-mono"
          >
            CC-1048
          </button>
        </div>

        {/* Footer Actions */}
        <div className="pt-4 border-t border-border-subtle flex items-center justify-end gap-3">
          <button
            onClick={onClose}
            type="button"
            className="h-10 px-4 rounded bg-surface-2 hover:bg-surface-3 text-text-secondary hover:text-text-primary font-body-default text-xs font-semibold border border-border-subtle transition-colors cursor-pointer"
          >
            CANCEL
          </button>
          <button
            onClick={handleJoin}
            disabled={status === "verifying" || !inputCode.trim()}
            type="button"
            className="h-10 px-6 rounded bg-primary-container hover:bg-[#F0FF70] text-[#080A0B] font-body-default font-bold text-xs flex items-center gap-2 transition-all active:scale-[0.99] cursor-pointer shadow-lg shadow-primary-container/10 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {status === "verifying" ? (
              <>
                <span>VERIFYING...</span>
                <span className="material-symbols-outlined text-[16px] animate-spin">sync</span>
              </>
            ) : (
              <>
                <span>CONNECT TO CHAMBER</span>
                <span className="material-symbols-outlined text-[16px]">sensors</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
