import { MatchRecord, MatchesSummaryTelemetry, SeasonArchiveSummary } from "@/types/matches";

export const MATCHES_SUMMARY: MatchesSummaryTelemetry = {
  currentElo: 1842,
  eloDelta: 18,
  rankTitle: "STACK HUNTER",
  tier: "TIER II",
  totalMatches: 69,
  rankedWins: 42,
  rankedLosses: 27,
  winRate: 61.8,
  winRateDelta: 4.2,
  recentForm: "WWWLW",
  season: "S04",
  seasonDelta: 73,
  peakElo: 1914,
  avgSolveDuration: "08:42",
  speedPercentile: "TOP 12% SPEED BRACKET",
};

export const SEASON_SUMMARY: SeasonArchiveSummary = {
  season: "SEASON 04",
  rankedRecord: "42–27",
  peakElo: 1914,
  bestStreak: "8 WINS",
  mostPlayedRuntime: "PYTHON 3.12 (68%)",
  totalVolume: 69,
};

// Seed dataset of 69 realistic high-stakes telemetry matches
export const ALL_MATCHES_DATA: MatchRecord[] = [
  // ================= TODAY (4 matches) =================
  {
    id: "CC-10482",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "BYTEGHOST",
      handle: "byteghost",
      initials: "BG",
      rankTitle: "STACK HUNTER",
      elo: 1796,
    },
    problem: {
      id: "CC-10482",
      title: "Circular Packet Route",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "08:24",
    testsPassed: 40,
    testsTotal: 40,
    eloDelta: 18,
    date: "2024-09-22",
    timestamp: "SEP 22 · 21:14",
    groupKey: "today",
    groupLabel: "TODAY — 22 SEP 2024",
  },
  {
    id: "CC-10471",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "NULLVECTOR",
      handle: "nullvector",
      initials: "NV",
      rankTitle: "KERNEL",
      elo: 1864,
    },
    problem: {
      id: "CC-10471",
      title: "Graph Relay Protocol",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "RUST 1.76",
    duration: "11:06",
    testsPassed: 37,
    testsTotal: 40,
    eloDelta: -16,
    date: "2024-09-22",
    timestamp: "SEP 22 · 18:43",
    groupKey: "today",
    groupLabel: "TODAY — 22 SEP 2024",
  },
  {
    id: "CC-10465",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "KAISEN_99",
      handle: "kaisen_99",
      initials: "K9",
      rankTitle: "STACK HUNTER",
      elo: 1810,
    },
    problem: {
      id: "CC-10465",
      title: "Subtree Isomorphism Validation",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "07:14",
    testsPassed: 35,
    testsTotal: 35,
    eloDelta: 22,
    date: "2024-09-22",
    timestamp: "SEP 22 · 15:20",
    groupKey: "today",
    groupLabel: "TODAY — 22 SEP 2024",
  },
  {
    id: "CC-10452",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "AXION_ROOT",
      handle: "axion_root",
      initials: "AR",
      rankTitle: "STACK HUNTER",
      elo: 1830,
    },
    problem: {
      id: "CC-10452",
      title: "Parallel DAG Pipeline Optimizer",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "14:02",
    testsPassed: 50,
    testsTotal: 50,
    eloDelta: 20,
    date: "2024-09-22",
    timestamp: "SEP 22 · 11:08",
    groupKey: "today",
    groupLabel: "TODAY — 22 SEP 2024",
  },

  // ================= YESTERDAY (4 matches) =================
  {
    id: "CC-10440",
    outcome: "WIN",
    mode: "private",
    opponent: {
      name: "STACKZERO",
      handle: "stackzero",
      initials: "SZ",
      rankTitle: "FELLOW",
      elo: 1820,
    },
    problem: {
      id: "CC-10440",
      title: "Island Routing Matrix",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "GO 1.22",
    duration: "06:48",
    testsPassed: 30,
    testsTotal: 30,
    eloDelta: 0,
    date: "2024-09-21",
    timestamp: "SEP 21 · 22:30",
    groupKey: "yesterday",
    groupLabel: "YESTERDAY — 21 SEP 2024",
  },
  {
    id: "CC-10433",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "V0RTEX_DEV",
      handle: "v0rtex_dev",
      initials: "VD",
      rankTitle: "KERNEL",
      elo: 1895,
    },
    problem: {
      id: "CC-10433",
      title: "LRU Cache Eviction Matrix",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "C++ 20",
    duration: "12:45",
    testsPassed: 42,
    testsTotal: 45,
    eloDelta: -19,
    date: "2024-09-21",
    timestamp: "SEP 21 · 19:15",
    groupKey: "yesterday",
    groupLabel: "YESTERDAY — 21 SEP 2024",
  },
  {
    id: "CC-10421",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "0xNULL",
      handle: "0xnull",
      initials: "0N",
      rankTitle: "DEV",
      elo: 1780,
    },
    problem: {
      id: "CC-10421",
      title: "Dynamic Memory Arena Allocation",
      difficulty: "MEDIUM",
      topic: "memory",
    },
    runtime: "PYTHON 3.12",
    duration: "06:45",
    testsPassed: 28,
    testsTotal: 28,
    eloDelta: 16,
    date: "2024-09-21",
    timestamp: "SEP 21 · 16:02",
    groupKey: "yesterday",
    groupLabel: "YESTERDAY — 21 SEP 2024",
  },
  {
    id: "CC-10410",
    outcome: "WIN",
    mode: "squad",
    opponent: {
      name: "SYNAPSE_X",
      handle: "synapse_x",
      initials: "SX",
      rankTitle: "STACK HUNTER",
      elo: 1840,
    },
    problem: {
      id: "CC-10410",
      title: "Zero-Knowledge Merkle Sieve",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "RUST 1.76",
    duration: "09:30",
    testsPassed: 60,
    testsTotal: 60,
    eloDelta: 14,
    date: "2024-09-21",
    timestamp: "SEP 21 · 13:50",
    groupKey: "yesterday",
    groupLabel: "YESTERDAY — 21 SEP 2024",
  },

  // ================= EARLIER THIS WEEK (7 matches) =================
  {
    id: "CC-10398",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "CIPHER_PUNK",
      handle: "cipher_punk",
      initials: "CP",
      rankTitle: "KERNEL",
      elo: 1855,
    },
    problem: {
      id: "CC-10398",
      title: "Quantum Bitmask Permutations",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "PYTHON 3.12",
    duration: "13:12",
    testsPassed: 31,
    testsTotal: 35,
    eloDelta: -15,
    date: "2024-09-20",
    timestamp: "SEP 20 · 21:05",
    groupKey: "earlier",
    groupLabel: "EARLIER THIS WEEK — 19–20 SEP 2024",
  },
  {
    id: "CC-10385",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "NEURAL_MIND",
      handle: "neural_mind",
      initials: "NM",
      rankTitle: "NOVICE",
      elo: 1775,
    },
    problem: {
      id: "CC-10385",
      title: "Sliding Window Latency Buffer",
      difficulty: "EASY",
      topic: "strings",
    },
    runtime: "TS 5.4",
    duration: "04:18",
    testsPassed: 20,
    testsTotal: 20,
    eloDelta: 0,
    date: "2024-09-20",
    timestamp: "SEP 20 · 18:22",
    groupKey: "earlier",
    groupLabel: "EARLIER THIS WEEK — 19–20 SEP 2024",
  },
  {
    id: "CC-10372",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "RUSTY_BLADE",
      handle: "rusty_blade",
      initials: "RB",
      rankTitle: "STACK HUNTER",
      elo: 1825,
    },
    problem: {
      id: "CC-10372",
      title: "B-Tree Lock-Free Balancing",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "11:50",
    testsPassed: 45,
    testsTotal: 45,
    eloDelta: 19,
    date: "2024-09-20",
    timestamp: "SEP 20 · 15:40",
    groupKey: "earlier",
    groupLabel: "EARLIER THIS WEEK — 19–20 SEP 2024",
  },
  {
    id: "CC-10360",
    outcome: "DRAW",
    mode: "ranked",
    opponent: {
      name: "KERNEL_PANIC",
      handle: "kernel_panic",
      initials: "KP",
      rankTitle: "STACK HUNTER",
      elo: 1842,
    },
    problem: {
      id: "CC-10360",
      title: "Distributed Mutex Deadlock Resolver",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "C++ 20",
    duration: "15:00",
    testsPassed: 40,
    testsTotal: 40,
    testsNote: "TIED",
    eloDelta: 0,
    date: "2024-09-20",
    timestamp: "SEP 20 · 12:10",
    groupKey: "earlier",
    groupLabel: "EARLIER THIS WEEK — 19–20 SEP 2024",
  },
  {
    id: "CC-10344",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "ECHO_DEV",
      handle: "echo_dev",
      initials: "ED",
      rankTitle: "DEV",
      elo: 1805,
    },
    problem: {
      id: "CC-10344",
      title: "Prefix Sum Matrix Compression",
      difficulty: "EASY",
      topic: "dp",
    },
    runtime: "PYTHON 3.12",
    duration: "05:12",
    testsPassed: 25,
    testsTotal: 25,
    eloDelta: 15,
    date: "2024-09-19",
    timestamp: "SEP 19 · 20:30",
    groupKey: "earlier",
    groupLabel: "EARLIER THIS WEEK — 19–20 SEP 2024",
  },
  {
    id: "CC-10331",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "GLITCH_RUNNER",
      handle: "glitch_runner",
      initials: "GR",
      rankTitle: "KERNEL",
      elo: 1880,
    },
    problem: {
      id: "CC-10331",
      title: "A* Hyper-Grid Pathfinding",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "RUST 1.76",
    duration: "14:20",
    testsPassed: 38,
    testsTotal: 42,
    eloDelta: -18,
    date: "2024-09-19",
    timestamp: "SEP 19 · 17:15",
    groupKey: "earlier",
    groupLabel: "EARLIER THIS WEEK — 19–20 SEP 2024",
  },
  {
    id: "CC-10318",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "PROTOCOL_7",
      handle: "protocol_7",
      initials: "P7",
      rankTitle: "DEV",
      elo: 1790,
    },
    problem: {
      id: "CC-10318",
      title: "Topological Sorter with Cycle Evasion",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "08:05",
    testsPassed: 32,
    testsTotal: 32,
    eloDelta: 17,
    date: "2024-09-19",
    timestamp: "SEP 19 · 14:00",
    groupKey: "earlier",
    groupLabel: "EARLIER THIS WEEK — 19–20 SEP 2024",
  },

  // ================= PREVIOUS WEEKS (Page 2, 3, 4, 5 data for testing) =================
  {
    id: "CC-10302",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "BINARY_SPECTRE",
      handle: "binary_spectre",
      initials: "BS",
      rankTitle: "STACK HUNTER",
      elo: 1815,
    },
    problem: {
      id: "CC-10302",
      title: "Bloom Filter Collision Minimizer",
      difficulty: "MEDIUM",
      topic: "memory",
    },
    runtime: "RUST 1.76",
    duration: "09:14",
    testsPassed: 36,
    testsTotal: 36,
    eloDelta: 18,
    date: "2024-09-18",
    timestamp: "SEP 18 · 22:10",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10295",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "HEX_WARRIOR",
      handle: "hex_warrior",
      initials: "HW",
      rankTitle: "NOVICE",
      elo: 1750,
    },
    problem: {
      id: "CC-10295",
      title: "Two-Pointer Bitwise XOR Swapper",
      difficulty: "EASY",
      topic: "memory",
    },
    runtime: "TS 5.4",
    duration: "03:45",
    testsPassed: 18,
    testsTotal: 18,
    eloDelta: 0,
    date: "2024-09-18",
    timestamp: "SEP 18 · 19:40",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10281",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "ALGO_TITAN",
      handle: "algo_titan",
      initials: "AT",
      rankTitle: "KERNEL",
      elo: 1910,
    },
    problem: {
      id: "CC-10281",
      title: "Red-Black Tree Rebalance Sweep",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "C++ 20",
    duration: "14:50",
    testsPassed: 44,
    testsTotal: 48,
    eloDelta: -17,
    date: "2024-09-18",
    timestamp: "SEP 18 · 16:30",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10274",
    outcome: "WIN",
    mode: "private",
    opponent: {
      name: "CYBER_NOMAD",
      handle: "cyber_nomad",
      initials: "CN",
      rankTitle: "FELLOW",
      elo: 1800,
    },
    problem: {
      id: "CC-10274",
      title: "Fast Fourier Transform Multiplier",
      difficulty: "HARD",
      topic: "dp",
    },
    runtime: "PYTHON 3.12",
    duration: "12:18",
    testsPassed: 40,
    testsTotal: 40,
    eloDelta: 0,
    date: "2024-09-17",
    timestamp: "SEP 17 · 21:55",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10260",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "DEV_NULL_88",
      handle: "dev_null_88",
      initials: "DN",
      rankTitle: "DEV",
      elo: 1770,
    },
    problem: {
      id: "CC-10260",
      title: "Segment Tree Range Query Matrix",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "08:44",
    testsPassed: 34,
    testsTotal: 34,
    eloDelta: 16,
    date: "2024-09-17",
    timestamp: "SEP 17 · 18:20",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10249",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "VOLT_SURGE",
      handle: "volt_surge",
      initials: "VS",
      rankTitle: "STACK HUNTER",
      elo: 1835,
    },
    problem: {
      id: "CC-10249",
      title: "Skip List Concurrency Lock",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "GO 1.22",
    duration: "10:32",
    testsPassed: 42,
    testsTotal: 42,
    eloDelta: 21,
    date: "2024-09-17",
    timestamp: "SEP 17 · 14:15",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10238",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "OBLIVION_CODE",
      handle: "oblivion_code",
      initials: "OC",
      rankTitle: "KERNEL",
      elo: 1890,
    },
    problem: {
      id: "CC-10238",
      title: "Raft Consensus Log Compaction",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "GO 1.22",
    duration: "15:22",
    testsPassed: 39,
    testsTotal: 45,
    eloDelta: -16,
    date: "2024-09-16",
    timestamp: "SEP 16 · 22:45",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10224",
    outcome: "WIN",
    mode: "squad",
    opponent: {
      name: "SIGMA_RUNNER",
      handle: "sigma_runner",
      initials: "SR",
      rankTitle: "STACK HUNTER",
      elo: 1822,
    },
    problem: {
      id: "CC-10224",
      title: "Kademlia DHT Peer Lookup",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "RUST 1.76",
    duration: "09:40",
    testsPassed: 52,
    testsTotal: 52,
    eloDelta: 15,
    date: "2024-09-16",
    timestamp: "SEP 16 · 19:10",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10212",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "ASYNC_SHADOW",
      handle: "async_shadow",
      initials: "AS",
      rankTitle: "STACK HUNTER",
      elo: 1812,
    },
    problem: {
      id: "CC-10212",
      title: "Trie-Based Autocomplete Streamer",
      difficulty: "MEDIUM",
      topic: "strings",
    },
    runtime: "PYTHON 3.12",
    duration: "07:35",
    testsPassed: 30,
    testsTotal: 30,
    eloDelta: 18,
    date: "2024-09-16",
    timestamp: "SEP 16 · 15:05",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10198",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "NEO_MATRIX",
      handle: "neo_matrix",
      initials: "NM",
      rankTitle: "NOVICE",
      elo: 1740,
    },
    problem: {
      id: "CC-10198",
      title: "Run-Length Encoding Compressor",
      difficulty: "EASY",
      topic: "strings",
    },
    runtime: "PYTHON 3.12",
    duration: "04:12",
    testsPassed: 22,
    testsTotal: 22,
    eloDelta: 0,
    date: "2024-09-15",
    timestamp: "SEP 15 · 21:30",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10185",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "BIT_CRUSHER",
      handle: "bit_crusher",
      initials: "BC",
      rankTitle: "STACK HUNTER",
      elo: 1845,
    },
    problem: {
      id: "CC-10185",
      title: "Heavy-Light Decomposition Query",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "C++ 20",
    duration: "13:48",
    testsPassed: 35,
    testsTotal: 40,
    eloDelta: -17,
    date: "2024-09-15",
    timestamp: "SEP 15 · 18:25",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10170",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "TRACE_ROUTE",
      handle: "trace_route",
      initials: "TR",
      rankTitle: "DEV",
      elo: 1795,
    },
    problem: {
      id: "CC-10170",
      title: "Maximum Bipartite Matching",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "08:19",
    testsPassed: 38,
    testsTotal: 38,
    eloDelta: 17,
    date: "2024-09-15",
    timestamp: "SEP 15 · 14:40",
    groupKey: "previous",
    groupLabel: "WEEK 38 — 15–18 SEP 2024",
  },
  {
    id: "CC-10156",
    outcome: "WIN",
    mode: "private",
    opponent: {
      name: "VALKYRIE_CPU",
      handle: "valkyrie_cpu",
      initials: "VC",
      rankTitle: "FELLOW",
      elo: 1830,
    },
    problem: {
      id: "CC-10156",
      title: "Suffix Array LCP Constructor",
      difficulty: "HARD",
      topic: "strings",
    },
    runtime: "RUST 1.76",
    duration: "11:15",
    testsPassed: 46,
    testsTotal: 46,
    eloDelta: 0,
    date: "2024-09-14",
    timestamp: "SEP 14 · 22:15",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10142",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "HYPER_THREAD",
      handle: "hyper_thread",
      initials: "HT",
      rankTitle: "STACK HUNTER",
      elo: 1820,
    },
    problem: {
      id: "CC-10142",
      title: "Dynamic Programming Knapsack Matrix",
      difficulty: "MEDIUM",
      topic: "dp",
    },
    runtime: "PYTHON 3.12",
    duration: "06:55",
    testsPassed: 28,
    testsTotal: 28,
    eloDelta: 19,
    date: "2024-09-14",
    timestamp: "SEP 14 · 19:00",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10130",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "CHRONO_LOCK",
      handle: "chrono_lock",
      initials: "CL",
      rankTitle: "KERNEL",
      elo: 1875,
    },
    problem: {
      id: "CC-10130",
      title: "Fibonacci Heap Priority Queue",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "C++ 20",
    duration: "14:10",
    testsPassed: 38,
    testsTotal: 42,
    eloDelta: -16,
    date: "2024-09-14",
    timestamp: "SEP 14 · 15:30",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10118",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "NEXUS_CORE",
      handle: "nexus_core",
      initials: "NC",
      rankTitle: "DEV",
      elo: 1785,
    },
    problem: {
      id: "CC-10118",
      title: "Fenwick Tree Inversion Counter",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "07:45",
    testsPassed: 32,
    testsTotal: 32,
    eloDelta: 16,
    date: "2024-09-13",
    timestamp: "SEP 13 · 21:10",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10105",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "PIXEL_HOUND",
      handle: "pixel_hound",
      initials: "PH",
      rankTitle: "NOVICE",
      elo: 1735,
    },
    problem: {
      id: "CC-10105",
      title: "Flood Fill Canvas Rasterizer",
      difficulty: "EASY",
      topic: "graphs",
    },
    runtime: "TS 5.4",
    duration: "04:30",
    testsPassed: 24,
    testsTotal: 24,
    eloDelta: 0,
    date: "2024-09-13",
    timestamp: "SEP 13 · 18:00",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10092",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "SUBROUTINE_X",
      handle: "subroutine_x",
      initials: "SX",
      rankTitle: "STACK HUNTER",
      elo: 1818,
    },
    problem: {
      id: "CC-10092",
      title: "Min-Cost Max-Flow Network Sieve",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "RUST 1.76",
    duration: "13:20",
    testsPassed: 48,
    testsTotal: 48,
    eloDelta: 22,
    date: "2024-09-13",
    timestamp: "SEP 13 · 14:15",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10079",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "QUANTUM_SPIN",
      handle: "quantum_spin",
      initials: "QS",
      rankTitle: "KERNEL",
      elo: 1902,
    },
    problem: {
      id: "CC-10079",
      title: "Simulated Annealing TSP Solver",
      difficulty: "HARD",
      topic: "dp",
    },
    runtime: "PYTHON 3.12",
    duration: "14:45",
    testsPassed: 36,
    testsTotal: 40,
    eloDelta: -18,
    date: "2024-09-12",
    timestamp: "SEP 12 · 22:00",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10065",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "LOGIC_GHOST",
      handle: "logic_ghost",
      initials: "LG",
      rankTitle: "STACK HUNTER",
      elo: 1808,
    },
    problem: {
      id: "CC-10065",
      title: "Bitwise Subset Convolution",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "C++ 20",
    duration: "10:50",
    testsPassed: 40,
    testsTotal: 40,
    eloDelta: 20,
    date: "2024-09-12",
    timestamp: "SEP 12 · 18:40",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10051",
    outcome: "WIN",
    mode: "private",
    opponent: {
      name: "CODE_MONK",
      handle: "code_monk",
      initials: "CM",
      rankTitle: "FELLOW",
      elo: 1815,
    },
    problem: {
      id: "CC-10051",
      title: "2-SAT Boolean Formula Evaluator",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "GO 1.22",
    duration: "08:15",
    testsPassed: 30,
    testsTotal: 30,
    eloDelta: 0,
    date: "2024-09-12",
    timestamp: "SEP 12 · 15:10",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10038",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "HEX_SHADOW",
      handle: "hex_shadow",
      initials: "HS",
      rankTitle: "DEV",
      elo: 1775,
    },
    problem: {
      id: "CC-10038",
      title: "Longest Increasing Subsequence O(N log N)",
      difficulty: "MEDIUM",
      topic: "dp",
    },
    runtime: "PYTHON 3.12",
    duration: "06:30",
    testsPassed: 35,
    testsTotal: 35,
    eloDelta: 16,
    date: "2024-09-11",
    timestamp: "SEP 11 · 21:50",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10024",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "VIPER_ASM",
      handle: "viper_asm",
      initials: "VA",
      rankTitle: "KERNEL",
      elo: 1865,
    },
    problem: {
      id: "CC-10024",
      title: "Zero-Allocation Circular Ring Buffer",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "RUST 1.76",
    duration: "13:30",
    testsPassed: 34,
    testsTotal: 40,
    eloDelta: -16,
    date: "2024-09-11",
    timestamp: "SEP 11 · 18:15",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-10010",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "STATIC_VOID",
      handle: "static_void",
      initials: "SV",
      rankTitle: "NOVICE",
      elo: 1720,
    },
    problem: {
      id: "CC-10010",
      title: "Valid Parentheses Stream Checker",
      difficulty: "EASY",
      topic: "strings",
    },
    runtime: "PYTHON 3.12",
    duration: "03:50",
    testsPassed: 20,
    testsTotal: 20,
    eloDelta: 0,
    date: "2024-09-11",
    timestamp: "SEP 11 · 14:00",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-09998",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "RADIX_PILOT",
      handle: "radix_pilot",
      initials: "RP",
      rankTitle: "STACK HUNTER",
      elo: 1805,
    },
    problem: {
      id: "CC-09998",
      title: "Radix Sort Fixed-Length Key Array",
      difficulty: "MEDIUM",
      topic: "memory",
    },
    runtime: "C++ 20",
    duration: "07:20",
    testsPassed: 30,
    testsTotal: 30,
    eloDelta: 17,
    date: "2024-09-10",
    timestamp: "SEP 10 · 22:30",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-09985",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "SYNTAX_TERROR",
      handle: "syntax_terror",
      initials: "ST",
      rankTitle: "DEV",
      elo: 1790,
    },
    problem: {
      id: "CC-09985",
      title: "Aho-Corasick Multi-Pattern Matcher",
      difficulty: "HARD",
      topic: "strings",
    },
    runtime: "PYTHON 3.12",
    duration: "11:40",
    testsPassed: 42,
    testsTotal: 42,
    eloDelta: 21,
    date: "2024-09-10",
    timestamp: "SEP 10 · 19:15",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-09971",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "COROUTINE_9",
      handle: "coroutine_9",
      initials: "C9",
      rankTitle: "KERNEL",
      elo: 1885,
    },
    problem: {
      id: "CC-09971",
      title: "Parallel Mergesort Task Pool",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "GO 1.22",
    duration: "14:15",
    testsPassed: 35,
    testsTotal: 40,
    eloDelta: -17,
    date: "2024-09-10",
    timestamp: "SEP 10 · 15:45",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-09958",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "MEM_LEAK",
      handle: "mem_leak",
      initials: "ML",
      rankTitle: "STACK HUNTER",
      elo: 1812,
    },
    problem: {
      id: "CC-09958",
      title: "Mark-and-Sweep Garbage Sieve",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "RUST 1.76",
    duration: "10:55",
    testsPassed: 45,
    testsTotal: 45,
    eloDelta: 20,
    date: "2024-09-09",
    timestamp: "SEP 09 · 21:40",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-09944",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "VOID_POINTER",
      handle: "void_pointer",
      initials: "VP",
      rankTitle: "NOVICE",
      elo: 1715,
    },
    problem: {
      id: "CC-09944",
      title: "Reverse Polish Notation Calculator",
      difficulty: "EASY",
      topic: "strings",
    },
    runtime: "TS 5.4",
    duration: "04:05",
    testsPassed: 20,
    testsTotal: 20,
    eloDelta: 0,
    date: "2024-09-09",
    timestamp: "SEP 09 · 18:20",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-09930",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "TRACE_DEV",
      handle: "trace_dev",
      initials: "TD",
      rankTitle: "DEV",
      elo: 1780,
    },
    problem: {
      id: "CC-09930",
      title: "Eulerian Path Finder in Directed Graph",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "07:50",
    testsPassed: 30,
    testsTotal: 30,
    eloDelta: 16,
    date: "2024-09-09",
    timestamp: "SEP 09 · 14:10",
    groupKey: "previous",
    groupLabel: "WEEK 37 — 08–14 SEP 2024",
  },
  {
    id: "CC-09916",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "ALGO_VIPER",
      handle: "algo_viper",
      initials: "AV",
      rankTitle: "KERNEL",
      elo: 1870,
    },
    problem: {
      id: "CC-09916",
      title: "Bridges and Articulation Points in Graph",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "13:55",
    testsPassed: 32,
    testsTotal: 38,
    eloDelta: -16,
    date: "2024-09-08",
    timestamp: "SEP 08 · 22:15",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09902",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "STACK_OVERLORD",
      handle: "stack_overlord",
      initials: "SO",
      rankTitle: "STACK HUNTER",
      elo: 1825,
    },
    problem: {
      id: "CC-09902",
      title: "Hopcroft-Karp Maximum Matching",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "C++ 20",
    duration: "11:20",
    testsPassed: 44,
    testsTotal: 44,
    eloDelta: 21,
    date: "2024-09-08",
    timestamp: "SEP 08 · 19:00",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09888",
    outcome: "WIN",
    mode: "private",
    opponent: {
      name: "TURBO_ENGINE",
      handle: "turbo_engine",
      initials: "TE",
      rankTitle: "FELLOW",
      elo: 1805,
    },
    problem: {
      id: "CC-09888",
      title: "Disjoint Set Union with Rollbacks",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "GO 1.22",
    duration: "08:10",
    testsPassed: 28,
    testsTotal: 28,
    eloDelta: 0,
    date: "2024-09-08",
    timestamp: "SEP 08 · 15:30",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09874",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "KINETIC_FLOW",
      handle: "kinetic_flow",
      initials: "KF",
      rankTitle: "DEV",
      elo: 1785,
    },
    problem: {
      id: "CC-09874",
      title: "Binary Indexed Tree Range Updates",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "06:40",
    testsPassed: 30,
    testsTotal: 30,
    eloDelta: 17,
    date: "2024-09-07",
    timestamp: "SEP 07 · 21:30",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09860",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "RABBIT_HOLE",
      handle: "rabbit_hole",
      initials: "RH",
      rankTitle: "NOVICE",
      elo: 1710,
    },
    problem: {
      id: "CC-09860",
      title: "Binary Search Rotated Array",
      difficulty: "EASY",
      topic: "memory",
    },
    runtime: "TS 5.4",
    duration: "03:30",
    testsPassed: 18,
    testsTotal: 18,
    eloDelta: 0,
    date: "2024-09-07",
    timestamp: "SEP 07 · 18:10",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09846",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "ZERO_POINT",
      handle: "zero_point",
      initials: "ZP",
      rankTitle: "KERNEL",
      elo: 1880,
    },
    problem: {
      id: "CC-09846",
      title: "Convex Hull Graham Scan",
      difficulty: "HARD",
      topic: "dp",
    },
    runtime: "C++ 20",
    duration: "13:10",
    testsPassed: 33,
    testsTotal: 40,
    eloDelta: -17,
    date: "2024-09-07",
    timestamp: "SEP 07 · 14:00",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09832",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "CHIP_DEV",
      handle: "chip_dev",
      initials: "CD",
      rankTitle: "STACK HUNTER",
      elo: 1815,
    },
    problem: {
      id: "CC-09832",
      title: "Z-Algorithm String Matching",
      difficulty: "MEDIUM",
      topic: "strings",
    },
    runtime: "PYTHON 3.12",
    duration: "07:15",
    testsPassed: 32,
    testsTotal: 32,
    eloDelta: 18,
    date: "2024-09-06",
    timestamp: "SEP 06 · 22:00",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09818",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "SPECTRE_9",
      handle: "spectre_9",
      initials: "S9",
      rankTitle: "DEV",
      elo: 1770,
    },
    problem: {
      id: "CC-09818",
      title: "Floyd-Warshall All-Pairs Shortest Path",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "08:00",
    testsPassed: 28,
    testsTotal: 28,
    eloDelta: 16,
    date: "2024-09-06",
    timestamp: "SEP 06 · 18:30",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09804",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "NEURAL_NET_4",
      handle: "neural_net_4",
      initials: "NN",
      rankTitle: "NOVICE",
      elo: 1725,
    },
    problem: {
      id: "CC-09804",
      title: "Merge Overlapping Intervals",
      difficulty: "EASY",
      topic: "dp",
    },
    runtime: "TS 5.4",
    duration: "04:10",
    testsPassed: 22,
    testsTotal: 22,
    eloDelta: 0,
    date: "2024-09-06",
    timestamp: "SEP 06 · 14:20",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09790",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "THREAD_LOCK",
      handle: "thread_lock",
      initials: "TL",
      rankTitle: "KERNEL",
      elo: 1895,
    },
    problem: {
      id: "CC-09790",
      title: "Lock-Free Ring Buffer CAS Enqueue",
      difficulty: "HARD",
      topic: "memory",
    },
    runtime: "RUST 1.76",
    duration: "14:40",
    testsPassed: 36,
    testsTotal: 42,
    eloDelta: -18,
    date: "2024-09-05",
    timestamp: "SEP 05 · 21:45",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09776",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "CYBER_CORE",
      handle: "cyber_core",
      initials: "CC",
      rankTitle: "STACK HUNTER",
      elo: 1820,
    },
    problem: {
      id: "CC-09776",
      title: "Dijkstra Priority Queue Optimization",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "07:30",
    testsPassed: 35,
    testsTotal: 35,
    eloDelta: 19,
    date: "2024-09-05",
    timestamp: "SEP 05 · 18:15",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09762",
    outcome: "WIN",
    mode: "private",
    opponent: {
      name: "ROOT_KIT_8",
      handle: "root_kit_8",
      initials: "RK",
      rankTitle: "FELLOW",
      elo: 1810,
    },
    problem: {
      id: "CC-09762",
      title: "Matrix Exponentiation Fibonacci Graph",
      difficulty: "MEDIUM",
      topic: "dp",
    },
    runtime: "GO 1.22",
    duration: "08:45",
    testsPassed: 26,
    testsTotal: 26,
    eloDelta: 0,
    date: "2024-09-05",
    timestamp: "SEP 05 · 14:00",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09748",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "QUANTUM_CODE",
      handle: "quantum_code",
      initials: "QC",
      rankTitle: "DEV",
      elo: 1780,
    },
    problem: {
      id: "CC-09748",
      title: "Kosaraju Strongly Connected Components",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "08:15",
    testsPassed: 32,
    testsTotal: 32,
    eloDelta: 16,
    date: "2024-09-04",
    timestamp: "SEP 04 · 22:10",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09734",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "ALPHA_PULSE",
      handle: "alpha_pulse",
      initials: "AP",
      rankTitle: "KERNEL",
      elo: 1875,
    },
    problem: {
      id: "CC-09734",
      title: "Centroid Decomposition on Trees",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "C++ 20",
    duration: "15:00",
    testsPassed: 34,
    testsTotal: 40,
    eloDelta: -16,
    date: "2024-09-04",
    timestamp: "SEP 04 · 18:40",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09720",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "HEX_DEV_1",
      handle: "hex_dev_1",
      initials: "HD",
      rankTitle: "NOVICE",
      elo: 1730,
    },
    problem: {
      id: "CC-09720",
      title: "Find First and Last Position in Sorted Array",
      difficulty: "EASY",
      topic: "memory",
    },
    runtime: "PYTHON 3.12",
    duration: "03:40",
    testsPassed: 20,
    testsTotal: 20,
    eloDelta: 0,
    date: "2024-09-04",
    timestamp: "SEP 04 · 14:15",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09706",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "VOLT_NINJA",
      handle: "volt_ninja",
      initials: "VN",
      rankTitle: "STACK HUNTER",
      elo: 1810,
    },
    problem: {
      id: "CC-09706",
      title: "Tarjan Offline Lowest Common Ancestor",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "PYTHON 3.12",
    duration: "10:20",
    testsPassed: 38,
    testsTotal: 38,
    eloDelta: 20,
    date: "2024-09-03",
    timestamp: "SEP 03 · 21:50",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09692",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "DELTA_WAVE",
      handle: "delta_wave",
      initials: "DW",
      rankTitle: "DEV",
      elo: 1775,
    },
    problem: {
      id: "CC-09692",
      title: "Ternary Search Unimodal Function",
      difficulty: "MEDIUM",
      topic: "dp",
    },
    runtime: "PYTHON 3.12",
    duration: "06:20",
    testsPassed: 28,
    testsTotal: 28,
    eloDelta: 17,
    date: "2024-09-03",
    timestamp: "SEP 03 · 18:10",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09678",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "CORE_DUMP",
      handle: "core_dump",
      initials: "CD",
      rankTitle: "KERNEL",
      elo: 1880,
    },
    problem: {
      id: "CC-09678",
      title: "Treap Randomized Binary Search Tree",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "C++ 20",
    duration: "14:30",
    testsPassed: 35,
    testsTotal: 42,
    eloDelta: -17,
    date: "2024-09-03",
    timestamp: "SEP 03 · 14:00",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09664",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "NANO_BYTE",
      handle: "nano_byte",
      initials: "NB",
      rankTitle: "STACK HUNTER",
      elo: 1805,
    },
    problem: {
      id: "CC-09664",
      title: "Binary Lifting Tree Node Distances",
      difficulty: "MEDIUM",
      topic: "graphs",
    },
    runtime: "RUST 1.76",
    duration: "08:15",
    testsPassed: 32,
    testsTotal: 32,
    eloDelta: 18,
    date: "2024-09-02",
    timestamp: "SEP 02 · 22:00",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09650",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "BIT_FLIP",
      handle: "bit_flip",
      initials: "BF",
      rankTitle: "NOVICE",
      elo: 1720,
    },
    problem: {
      id: "CC-09650",
      title: "Number of 1 Bits Hamming Weight",
      difficulty: "EASY",
      topic: "memory",
    },
    runtime: "TS 5.4",
    duration: "03:15",
    testsPassed: 16,
    testsTotal: 16,
    eloDelta: 0,
    date: "2024-09-02",
    timestamp: "SEP 02 · 18:30",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09636",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "CHIP_RUNNER",
      handle: "chip_runner",
      initials: "CR",
      rankTitle: "DEV",
      elo: 1790,
    },
    problem: {
      id: "CC-09636",
      title: "KMP String Search Preprocessing",
      difficulty: "MEDIUM",
      topic: "strings",
    },
    runtime: "PYTHON 3.12",
    duration: "06:45",
    testsPassed: 30,
    testsTotal: 30,
    eloDelta: 16,
    date: "2024-09-02",
    timestamp: "SEP 02 · 14:10",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09622",
    outcome: "LOSS",
    mode: "ranked",
    opponent: {
      name: "GLITCH_CORE",
      handle: "glitch_core",
      initials: "GC",
      rankTitle: "KERNEL",
      elo: 1870,
    },
    problem: {
      id: "CC-09622",
      title: "Link-Cut Tree Dynamic Connectivity",
      difficulty: "HARD",
      topic: "graphs",
    },
    runtime: "C++ 20",
    duration: "14:50",
    testsPassed: 32,
    testsTotal: 40,
    eloDelta: -16,
    date: "2024-09-01",
    timestamp: "SEP 01 · 21:30",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09608",
    outcome: "WIN",
    mode: "ranked",
    opponent: {
      name: "SUB_ZERO_DEV",
      handle: "sub_zero_dev",
      initials: "SZ",
      rankTitle: "STACK HUNTER",
      elo: 1815,
    },
    problem: {
      id: "CC-09608",
      title: "Bitmask Dynamic Programming TSP",
      difficulty: "HARD",
      topic: "dp",
    },
    runtime: "PYTHON 3.12",
    duration: "11:10",
    testsPassed: 40,
    testsTotal: 40,
    eloDelta: 20,
    date: "2024-09-01",
    timestamp: "SEP 01 · 18:00",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
  {
    id: "CC-09594",
    outcome: "WIN",
    mode: "casual",
    opponent: {
      name: "CODE_RUNNER_1",
      handle: "code_runner_1",
      initials: "CR",
      rankTitle: "NOVICE",
      elo: 1710,
    },
    problem: {
      id: "CC-09594",
      title: "Valid Anagram Counter",
      difficulty: "EASY",
      topic: "strings",
    },
    runtime: "PYTHON 3.12",
    duration: "03:10",
    testsPassed: 18,
    testsTotal: 18,
    eloDelta: 0,
    date: "2024-09-01",
    timestamp: "SEP 01 · 14:00",
    groupKey: "previous",
    groupLabel: "WEEK 36 — 01–07 SEP 2024",
  },
];
