import { RankProfileData } from "@/types/rank";

export const RANK_PROFILE_DATA: RankProfileData = {
  tierId: "#OVL-02",
  tierName: "OVERLORD II",
  tierRoman: "TIER V",
  tagline: "Adversarial Heuristic Synthesis & Non-linear Graph Specialization",
  currentXp: 9800,
  targetXp: 12000,
  xpRemaining: 2200,
  nextTierName: "OVERLORD I",
  divisionProgressPercent: 45, // 1800 / 4000 in bracket (8000 -> 12000)
  competitiveElo: 1842,
  topSegmentPercent: 1.4,
  seasonPeakRank: "OVERLORD I",
  seasonPeakDate: "Achieved Sep 14",
  globalRank: 1842,
  cluster: "Cluster US-EAST",
  apexTargetTier: "NEURAL_GOD",
  apexTargetXp: 20000,
  apexProgressPercent: 49,
  performance: {
    startedAt: "ARCHITECT II",
    startedXp: 6100,
    xpAccumulated: 3700,
    rankedRecord: "42W – 27L",
    winProbability: 60.8,
    streakPeak: 8,
    activeStreak: "1 W",
  },
  divisions: [
    {
      name: "DIV III",
      xpRequired: 8000,
      status: "COMPLETED",
    },
    {
      name: "DIV II (CURRENT)",
      xpRequired: 9800,
      status: "CURRENT",
      progressPercent: 45,
    },
    {
      name: "DIV I",
      xpRequired: 12000,
      status: "LOCKED",
    },
  ],
  recentMovement: [
    {
      id: "mv-1",
      matchId: "CC-10482",
      outcome: "VICTORY",
      opponent: "BYTEGHOST",
      topic: "DP Matrix Optimization",
      xpDelta: 180,
      eloDelta: 18,
      xpBefore: 9620,
      xpAfter: 9800,
      date: "SEP 27",
    },
    {
      id: "mv-2",
      matchId: "CC-10471",
      outcome: "DEFEAT",
      opponent: "VOIDRUNNER",
      topic: "Bitmask TSP Search",
      xpDelta: -95,
      eloDelta: -14,
      xpBefore: 9715,
      xpAfter: 9620,
      date: "SEP 26",
    },
    {
      id: "mv-3",
      matchId: "CC-10465",
      outcome: "VICTORY",
      opponent: "SYNAPSE_X",
      topic: "Red-Black Rotation",
      xpDelta: 210,
      eloDelta: 22,
      xpBefore: 9505,
      xpAfter: 9715,
      date: "SEP 25",
    },
    {
      id: "mv-4",
      matchId: "CC-10452",
      outcome: "VICTORY",
      opponent: "ZERO_POINT",
      topic: "Flow Min-Cut Logic",
      xpDelta: 175,
      eloDelta: 17,
      xpBefore: 9330,
      xpAfter: 9505,
      date: "SEP 24",
    },
    {
      id: "mv-5",
      matchId: "CC-10440",
      outcome: "DEFEAT",
      opponent: "STACKZERO",
      topic: "Segment Tree Lazy Propagation",
      xpDelta: -110,
      eloDelta: -16,
      xpBefore: 9440,
      xpAfter: 9330,
      date: "SEP 22",
    },
  ],
  tierLadder: [
    {
      id: "t6",
      name: "NEURAL_GOD",
      tierNumber: 6,
      badgeTag: "APEX TIER",
      description:
        "Pinnacle adversarial mastery. Zero margin for algorithmic sub-optimality. Top 0.1% combatants.",
      bracket: "20,000+ XP",
      entryThreshold: "20,000+ XP",
      status: "LOCKED",
    },
    {
      id: "t5",
      name: "OVERLORD",
      tierNumber: 5,
      badgeTag: "CURRENT TIER",
      description:
        "Complex state synthesis, distributed game theory, flow mechanics, dynamic memory control.",
      bracket: "8,000 – 14,000 XP",
      status: "CURRENT",
      divisions: [
        { name: "DIV III", xp: "8,000 XP", isCompleted: true },
        { name: "DIV II", xp: "9,800 XP", isCurrent: true },
        { name: "DIV I", xp: "12,000 XP", isCurrent: false },
      ],
    },
    {
      id: "t4",
      name: "ARCHITECT",
      tierNumber: 4,
      badgeTag: "SURPASSED",
      description:
        "Distributed logic, advanced optimization, topological sorting, segment and binary indexed trees.",
      bracket: "5,000 – 7,999 XP",
      status: "CLEARED",
      divisionsSummary: "DIV III • DIV II • DIV I CLEARED",
    },
    {
      id: "t3",
      name: "EXECUTOR",
      tierNumber: 3,
      badgeTag: "SURPASSED",
      description:
        "Graph traversal (Dijkstra, Bellman-Ford), multi-dimensional dynamic programming, memoization.",
      bracket: "3,000 – 4,999 XP",
      status: "CLEARED",
      divisionsSummary: "DIV III • DIV II • DIV I CLEARED",
    },
    {
      id: "t2",
      name: "COMPILER",
      tierNumber: 2,
      badgeTag: "SURPASSED",
      description:
        "Linear and non-linear data structures, binary trees, heaps, amortized Big-O analysis.",
      bracket: "1,500 – 2,999 XP",
      status: "CLEARED",
      divisionsSummary: "DIV III • DIV II • DIV I CLEARED",
    },
    {
      id: "t1",
      name: "SCRIPTER",
      tierNumber: 1,
      badgeTag: "ORIGIN",
      description:
        "Algorithmic foundations, pointer arithmetic, string manipulation, sorting heuristics.",
      bracket: "0 – 1,499 XP",
      status: "CLEARED",
      divisionsSummary: "DIV III • DIV II • DIV I CLEARED",
    },
  ],
};
